name: zenspace
description: "A space for your thoughts"
publish_to: 'none'

version: 1.0.0+1
environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # State Management
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  # Backend & Authentication
  supabase_flutter: ^2.3.4
  flutter_dotenv: ^5.1.0
  # UI Components
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1
  smooth_page_indicator: ^1.1.0
  # Utils
  intl: ^0.19.0
  logger: ^2.0.2+1
  url_launcher: ^6.2.5
  shared_preferences: ^2.2.2
  http: ^1.2.0
  record: ^5.0.4
  audioplayers: ^5.2.1
  path_provider: ^2.1.2
  loading_animation_widget: ^1.2.0+4
  speech_to_text: ^7.0.0
  flutter_tts: ^4.2.2
  google_generative_ai: ^0.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  device_preview: ^1.1.0
flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/images/
    - assets/icons/
    - assets/illustrations/
    - assets/audio/
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  web:
    generate: false
  windows:
    generate: false
  macos:
    generate: false
